In [1]:
import numpy as np
import torch

In [2]:
a = np.arange(0,21,2)

In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [4]:
a_torch = torch.from_numpy(a).type(torch.LongTensor).to(device)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
train_node_indice, test_node_indice = train_test_split(np.arange(10),random_state=0)

In [7]:
a_torch[train_node_indice]

tensor([18,  2, 12, 14,  6,  0, 10])

In [8]:
a_torch[test_node_indice]

tensor([ 4, 16,  8])

In [11]:
b = np.random.rand(256,10)

In [13]:
b_torch = torch.from_numpy(b)

In [15]:
b_torch[train_node_indice]

torch.Size([7, 10])

In [28]:
c = np.array([[1,2,3],[4,5,6],[7,8,11]])

In [29]:
c_torch = torch.from_numpy(c).float()

In [30]:
torch.nn.functional.softmax(c_torch,dim=1)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652],
        [0.0171, 0.0466, 0.9362]])

In [31]:
import torch.nn.functional as F

In [36]:
train_z = torch.from_numpy(np.random.rand(10,2))

In [44]:
torch.exp(F.softmax(train_z,1))

tensor([[1.5576, 1.7452],
        [1.6612, 1.6363],
        [1.4281, 1.9035],
        [1.5541, 1.7491],
        [1.5755, 1.7253],
        [1.6322, 1.6654],
        [1.8588, 1.4624],
        [1.5065, 1.8043],
        [1.4771, 1.8402],
        [1.5476, 1.7564]], dtype=torch.float64)

In [47]:
>>> import numpy as np
>>> from sklearn.metrics import roc_auc_score
>>> y_true = np.array([1, 1, 0, 0])
>>> y_scores = np.array([0.1, 0.4, 0.35, 0.8])
>>> roc_auc_score(y_true, y_scores)

0.25