# Signed Graph Convolutional Network(SGCN)を用いたFraud User Detection

In [1]:
!git branch

  balance_theory
  balance_theory2
  master
  new_balance_theory2
* subgraph_training_theory2


```sh
pip install -r /home/ubuntu/SGCN/requirements.txt
pip install torch_scatter
pip install torch_sparse
pip install easydict
```


In [2]:
from sgcn import SignedGCNTrainer, SignedGCNPredictor
from parser import parameter_parser
from utils import tab_printer, read_graph, score_printer, save_logs
import easydict
import argparse
import pandas as pd
import numpy as np
import torch
import json
import networkx as nx
from sklearn.metrics import roc_auc_score, roc_curve, auc
from sklearn.metrics import accuracy_score,confusion_matrix
from IPython.display import display
import matplotlib.pyplot as plt
%matplotlib inline

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))


In [ ]:
data_name = input('データセット：')

In [ ]:
args = easydict.EasyDict({
        "edge_path": f'../input/{data_name}/{data_name}_network.csv',#'../input/{data_name}/user_network.csv',
        "features_path":  f'../input/{data_name}/{data_name}_node_feature.csv',#'../input/{data_name}/user_network.csv',
        "nodes_path": f'../input/{data_name}/{data_name}_gt.csv',
        "embedding_path": f'../tmp/embedding/{data_name}_sgcn_feature05.pkl', # tmp folder for cross-validation
        "regression_weights_path": f'../tmp/weights/{data_name}_sgcn_feature05.pkl',
        "inductive_model_path": None, # f'../output/inductive/{data_name}_model', # or None
        "log_path": f'../logs/{data_name}_logs_feature05.json',
        "epochs":300,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 0.0,
        "learning_rate": 0.001,  
        "weight_decay": 10e-4, 
        # "layers": [64, 32,16,8],
        "layers": [32, ],
        "spectral_features":False,
        "general_features": True,  
        "sample_num":None,
        "class_weights":False,
        "node_under_sampling":False,
        "hidden_residual":False,
        "eval_freq":1,
})

In [ ]:
display(pd.io.json.json_normalize(args).T)

## 10-fold cross-validation
- train : validation : test = 6:3:1

In [ ]:
#tab_printer(args)
edges, nodes_dict = read_graph(args) # nodes_dict['indice']:node_id , nodes_dict['label'] : label

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
kf = StratifiedKFold(n_splits=10)
all_indice = nodes_dict['indice']
all_labels = nodes_dict['label']
auc_scores = []

In [ ]:
for i, (train_index, test_index) in enumerate(kf.split(X=nodes_dict['indice'],y=nodes_dict['label'])):
    print("==== Training Phase ====")
    print(f'{i}-th fold')
    # training
    train_node_indice = all_indice[train_index]
    train_node_labels = all_labels[train_index]
    print(f'labels:{np.unique(train_node_labels,return_counts=True)}')
    tmp_nodes_dict = {}
    tmp_nodes_dict['all_ncount'] = nodes_dict['all_ncount']
    tmp_nodes_dict['indice'] = train_node_indice
    tmp_nodes_dict['label'] = train_node_labels
    trainer = SignedGCNTrainer(args, edges, tmp_nodes_dict)
    trainer.setup_dataset()
    trainer.create_and_train_model()
    
    if args.test_size > 0:
        # trainer.save_model() ## trainer.create_and_train_model()のなかで，すでにbest_modelが保存されている．
        # score_printer(trainer.logs)
        display(pd.DataFrame(trainer.logs['performance']))
        save_logs(args, trainer.logs)

    # test
    print("==== Test Phase ====")
    test_node_indice = all_indice[test_index]
    test_node_labels = all_labels[test_index]
    # feature = pd.read_csv(args.embedding_path,index_col='id').values
    feature = pd.read_pickle(args.embedding_path).drop('id',1).values
    test_feature = feature[test_node_indice]
    # weight = pd.read_csv(args.regression_weights_path)
    weight = pd.read_pickle(args.regression_weights_path)
    predictions = np.dot(test_feature,weight.values.T)
    probabilities = torch.nn.functional.softmax(torch.from_numpy(predictions)).numpy()
    predict_labels = probabilities.argmax(1)
    auc_score = roc_auc_score(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_score=probabilities[:,1])
    auc_scores.append(auc_score)
    cmx = confusion_matrix(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_pred=predict_labels)
    print(f"{i}-th fold's auc_score:{auc_score}")
    print(cmx)
    print()
    

In [ ]:
np.mean(auc_scores)

In [ ]:
_ = plt.hist(probabilities[:,1][test_node_labels==1],alpha=0.5,bins=10)
_ = plt.hist(probabilities[:,1][test_node_labels==-1],alpha=0.5,bins=10)
# plt.xlim(0,0.03)

# new_new_balance_theoryの結果
結果 (32,) (non-class-weights,10e-4, test_size=0.33,lamb=0,lr=0.001)　⬅️これに決定
- amazon :  0.8655989752374083
- alpha : 0.974480519480
- otc : 

結果 (32,16) (non-class-weights,10e-4, test_size=0.33,lamb=0,lr=0.001)　
- amazon :  0.876279480706
- alpha : 0.977922077922
- otc : 0.99072039072
- epinions : 0.9768200116


結果 (32,16, 8) (non-class-weights,10e-4, test_size=0.33, lamb=0)
- amazon : 0.8786657350643106
- alpha : 
- otc : 

結果 (32,16, 8, 8) (non-class-weights,10e-4, test_size=0.33, lamb=0)
- amazon : 0.8778590500661
- alpha : 
- otc : 



# new_balance_theoryの結果


結果 (32,16) (non-class-weights,10e-3, test_size=0.33)
- amazon : 0.8650228
- alpha : 0.984
- otc : 0.9979548

結果 (32,16, 8) (non-class-weights,10e-4, test_size=0.33)
- amazon : 0.8722951
- alpha : 
- otc : 

結果 (32,16) (non-class-weights,10e-3, test_size-0.5)
- amazon : 
- alpha : 
- otc : 

結果 (32,32,32,32) (non-class-weights,10e-3, hidden_residual,) (100 epoch)
- amazon : 0.86009158252
- alpha : 
- otc : 

結果 (32,32,32,) (class-weights,10e-3,hidden_residual) (100 epoch)
- amazon : 0.864321831
- alpha : 
- otc : 

---

結果 (32,) (no-class-weights, 0.33)
- amazon : 0.856184081
- alpha : 0.983
- otc : 0.998

結果 (32,16) (no-class-weights,test_size=0.33,weight_decay=10e-5)
- amazon : 0.871
- alpha : 0.9828
- otc : 0.997

結果 (32,16,8) (no-class-weights,test_size=0.33)
- amazon : 0.867
- alpha : 0.97123376
- otc : 0.9883699633699635

結果 (32,16,8) (no-class-weights,test_size=0.33,lamb=0)
- amazon : 0.871944
- alpha : 0.96454545
- otc : 0.994810744810

結果 (32,32,32) (no-class-weights,test_size=0.33,lamb=1.0,residual)
- amazon : 0.869
- alpha : 0.
- otc : 0.

結果 (32,16) (no-class-weights,test_size=0.33,weight_decay=10e-3)
- amazon : 0.871668935569  -->  0.866652196778459
- alpha : 0.9868181818181819 --> 0.9778071928071927
- otc : 0.9963980463980464  --> 0.99557387057

結果 (32,16) (no-class-weights,test_size=0.33,weight_decay=10e-3, amazon_unsigned)
- amazon : 
- alpha : 0.9868181818181819 --> 0.9778071928071927
- otc : 0.9963980463980464  --> 0.99557387057

---

結果 (32,16) (no-class-weights,test_size=0.66)
- amazon : 0.8635876758
- alpha : 0.9831
- otc : 0.993

結果 (64,32)
- amazon : 0.8597141032576031
- alpha : 
- otc : 

結果 (64,32,16,8)
- amazon : 0.8516649987979326
- alpha : 
- otc : 

結果
- amazon : 0.8704, (weighted classes loss : 0.871)
- alpha : (sampled: 0.9804), (normal: 0.9857)
- epinions : 
- otc : (0.9947), (normal:0.996)

## single-validation

In [ ]:
args = easydict.EasyDict({
        "edge_path": '../input/amazon/amazon_network.csv',#'../input/amazon/user_network.csv',
        "features_path":  '../input/amazon/amazon_node_feature.csv',#'../input/amazon/user_network.csv',
        "nodes_path": '../input/amazon/amazon_gt.csv',
        "embedding_path": '../tmp/embedding/amazon_sgcn_feature05.pkl', # tmp folder for cross-validation
        "regression_weights_path": '../tmp/weights/amazon_sgcn_feature05.pkl',
        "inductive_model_path": '../output/inductive/amazon_model', # or None
        "log_path": '../logs/amazon_logs_feature05.json',
        "epochs":500,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 1.0,
        "learning_rate": 0.005,  
        "weight_decay": 10e-5, 
        # "layers": [64, 32,16,8],
        "layers": [32,16],
        "spectral_features":False,
        "general_features": True,  
        "sample_num":None,
        "class_weights":False,
        "node_under_sampling":False,
})

In [ ]:
#tab_printer(args)
edges, nodes_dict = read_graph(args) # nodes_dict['indice']:node_id , nodes_dict['label'] : label

In [ ]:
trainer = SignedGCNTrainer(args, edges, nodes_dict)
trainer.setup_dataset()
trainer.create_and_train_model()

In [ ]:
if args.test_size > 0:
    trainer.save_model()
    # score_printer(trainer.logs)
    display(pd.DataFrame(trainer.logs['performance']))
    save_logs(args, trainer.logs)

#### inductive settings

In [ ]:
new_args = easydict.EasyDict({
        "edge_path": '../input/amazon_music/amazon_music_network.csv',#'../input/amazon_music/user_network.csv',
        "features_path":  '../input/amazon_music/amazon_music_node_feature.csv',#'../input/amazon_music/user_network.csv',
        "nodes_path": '../input/amazon_music/amazon_music_gt.csv',
        "embedding_path": '../tmp/embedding/amazon_music_sgcn_feature05.csv', # tmp folder for cross-validation
        "regression_weights_path": '../tmp/weights/amazon_music_sgcn_feature05.csv',
        "inductive_model_path": None, # '../output/inductive/amazon_music_model', # or None
        "log_path": '../logs/amazon_music_logs_feature05.json',
        "epochs":300,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 1.0,
        "learning_rate": 0.005,  
        "weight_decay": 10e-5, 
        # "layers": [64, 32,16,8],
        "layers": [32, 16],
        "spectral_features":False,
        "general_features": True,  
        "class_weights":False,
        "sample_num":None,
        "node_under_sampling":False,
})

In [ ]:
new_edges, new_nodes_dict = read_graph(new_args)

X = np.array(pd.read_csv('../input/amazon_elec/amazon_elec_node_feature.csv')) # general node features

In [ ]:
predictor = SignedGCNPredictor(new_args, '../output/inductive/amazon_model', X, new_edges,new_nodes_dict)

In [ ]:
predictions = predictor.predict()
predict_labels = predictions.argmax(1)

In [ ]:
y_true = new_nodes_dict['label']

In [ ]:
roc_auc_score(y_true=[1 if i==-1 else 0 for i in new_nodes_dict['label']],y_score=predictions[:,1][new_nodes_dict['indice']])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
confusion_matrix([1 if i==-1 else 0 for i in new_nodes_dict['label']],predict_labels[new_nodes_dict['indice']])

In [ ]:
y_true.shape

In [ ]:
_ = plt.hist(predictions[:,1][new_nodes_dict['indice']][y_true==1],alpha=0.5,bins=10)
_ = plt.hist(predictions[:,1][new_nodes_dict['indice']][y_true==-1],alpha=0.5,bins=10)

結果
- amazon
    - elec : 0.80787063118
    - movie : 0.55
    - music : 0.76
    

In [ ]:
import json

In [ ]:
performance = pd.DataFrame(json.load(open('../logs/otc_logs_feature05.json','r'))['performance'])

performance.columns = performance.iloc[0,:]

performance = performance.iloc[1:,:]

In [ ]:
performance['AUC'].plot()

In [ ]:
feature = pd.read_csv(args.embedding_path,index_col='id')

weight = pd.read_csv(args.regression_weights_path)

In [ ]:
predictions = np.dot(feature.values,weight.values.T)

In [ ]:
probabilities = torch.nn.functional.softmax(torch.from_numpy(predictions)).numpy()

In [ ]:
predict_labels = probabilities.argmax(1)

In [ ]:
roc_auc_score(y_true=[0 if i==-1 else 1 for i in nodes_dict['label']],y_score=probabilities[:,1][nodes_dict['indice']])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
confusion_matrix([0 if i==-1 else 1 for i in nodes_dict['label']],predict_labels[nodes_dict['indice']])

# TODO

#### for epinions dataset

In [3]:
data_name = 'epinions'

In [4]:
args = easydict.EasyDict({
        "edge_path": f'../input/{data_name}/{data_name}_network.csv',#'../input/{data_name}/user_network.csv',
        "features_path":  f'../input/{data_name}/{data_name}_node_feature.csv',#'../input/{data_name}/user_network.csv',
        "nodes_path": f'../input/{data_name}/{data_name}_gt.csv',
        "embedding_path": f'../tmp/embedding/{data_name}_sgcn_feature05.pkl', # tmp folder for cross-validation
        "regression_weights_path": f'../tmp/weights/{data_name}_sgcn_feature05.pkl',
        "inductive_model_path": f'../output/inductive/{data_name}_model', # or None
        "log_path": f'../logs/{data_name}_logs_feature05.json',
        "epochs":300,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 0.0,
        "learning_rate": 0.001,  
        "weight_decay": 10e-4, 
        # "layers": [64, 32,16,8],
        "layers": [32, 16],
        "spectral_features":False,
        "general_features": True,  
        "sample_num":None,
        "class_weights":False,
        "node_under_sampling":False,
        "hidden_residual":False,
        "eval_freq":1,
        "subgraph_training":True,
})

In [5]:
display(pd.io.json.json_normalize(args).T)

0
class_weights                                                   False
edge_path                      ../input/epinions/epinions_network.csv
embedding_path           ../tmp/embedding/epinions_sgcn_feature05.pkl
epochs                                                            300
eval_freq                                                           1
features_path             ../input/epinions/epinions_node_feature.csv
general_features                                                 True
hidden_residual                                                 False
inductive_model_path               ../output/inductive/epinions_model
lamb                                                                0
layers                                                       [32, 16]
learning_rate                                                   0.001
log_path                         ../logs/epinions_logs_feature05.json
node_under_sampling                                             False
nodes_path                          ../input/epinions/epinions_gt.csv
reduction_dimensions                                               30
reduction_iterations                                              128
regression_weights_path    ../tmp/weights/epinions_sgcn_feature05.pkl
sample_num                                                       None
seed                                                               42
spectral_features                                               False
subgraph_training                                                True
test_size                                                        0.33
weight_decay                                                    0.001

In [6]:
#tab_printer(args)
edges, nodes_dict = read_graph(args) # nodes_dict['indice']:node_id , nodes_dict['label'] : label

In [7]:
test_X = np.array(pd.read_csv(args.features_path))

In [8]:
def subgraph_making(args,edges,nodes_dict,sample_node_num,train_node_indice_original):
    original_network_df = pd.read_csv(args.edge_path)

    sampled_node_indice = set(np.random.choice(np.arange(nodes_dict['all_ncount']), 20000, replace=False)) | set(train_node_indice_original)

    sub_network_df = \
        original_network_df.loc[(original_network_df.id1_.isin(sampled_node_indice)) & (original_network_df.id2_.isin(sampled_node_indice))]

    original_gt_df = pd.read_csv(args.nodes_path)

    sub_gt_df = \
        original_gt_df.copy().loc[(original_gt_df.node_id.isin(sub_network_df.id1_)) & (original_gt_df.node_id.isin(sub_network_df.id2_))]

    from sklearn.preprocessing import LabelEncoder

    subGraph_map_encoder = LabelEncoder()

    subGraph_map_encoder.fit(list(set(sub_network_df.id1_) | set(sub_network_df.id2_) | set(sub_gt_df.node_id)))

    sub_gt_df['node_id'] = subGraph_map_encoder.transform(sub_gt_df.node_id)

    sub_network_df['id1_'] = subGraph_map_encoder.transform(sub_network_df.id1_)

    sub_network_df['id2_'] = subGraph_map_encoder.transform(sub_network_df.id2_)

    sub_edges = {}

    sub_edges['positive_edges'] = sub_network_df.loc[sub_network_df.weight==1,['id1_','id2_']].values.tolist()

    sub_edges['negative_edges'] = sub_network_df.loc[sub_network_df.weight==-1,['id1_','id2_']].values.tolist()

    sub_edges['ecount'] = len(sub_network_df)

    sub_edges['ncount'] = len(set(sub_network_df['id1_']) | set(sub_network_df['id2_']))

    sub_nodes_dict = {}

    sub_nodes_dict['indice'] = sub_gt_df.node_id.values
    sub_nodes_dict['label'] = sub_gt_df.label.values

    sub_nodes_dict['all_ncount'] = len(set(sub_network_df.id1_) | set(sub_network_df.id2_) | set(sub_gt_df.node_id))

    sub_nodes_dict['subgraph_map_from_original_feature'] = subGraph_map_encoder.classes_    
    return sub_edges, sub_nodes_dict, subGraph_map_encoder

In [11]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=10)
all_indice = nodes_dict['indice']
all_labels = nodes_dict['label']
auc_scores = []

In [12]:
for i, (train_index, test_index) in enumerate(kf.split(X=nodes_dict['indice'],y=nodes_dict['label'])):
    print("==== Training Phase ====")
    print(f'{i}-th fold')
    # training
    train_node_indice_original = all_indice[train_index] #⬅️これは元々のグラフのnode_indice

    # extract sub-graph
    sub_edges, sub_nodes_dict,subGraph_map_encoder = subgraph_making(args,edges,nodes_dict,50000, [])
                                                                     # np.random.choice(train_node_indice_original,1000))
    
    train_indice_boolean_judger = np.isin(subGraph_map_encoder.inverse_transform(sub_nodes_dict['indice']),train_node_indice_original)
    train_node_indice = sub_nodes_dict['indice'][train_indice_boolean_judger]
    train_node_labels = sub_nodes_dict['label'][train_indice_boolean_judger]
    print(f'labels:{np.unique(train_node_labels,return_counts=True)}')
    tmp_nodes_dict = {}
    tmp_nodes_dict['all_ncount'] = sub_nodes_dict['all_ncount']
    tmp_nodes_dict['indice'] = train_node_indice
    tmp_nodes_dict['label'] = train_node_labels
    tmp_nodes_dict['subgraph_map_from_original_feature'] = subGraph_map_encoder.classes_
    trainer = SignedGCNTrainer(args, sub_edges, tmp_nodes_dict)
    trainer.setup_dataset()
    trainer.create_and_train_model()
    
    if args.test_size > 0:
        # trainer.save_model() ## trainer.create_and_train_model()のなかで，すでにbest_modelが保存されている．
        # score_printer(trainer.logs)
        display(pd.DataFrame(trainer.logs['performance']))
        save_logs(args, trainer.logs)

    # test
    print("==== Test Phase ====")
    test_node_indice = all_indice[test_index]
    test_node_labels = all_labels[test_index]
    predictor = SignedGCNPredictor(args, args.inductive_model_path, test_X, edges,nodes_dict)
    predictions = predictor.predict()
    predict_labels = predictions.argmax(1)
    auc_score = roc_auc_score(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_score=predictions[:,1][test_node_indice])
    auc_scores.append(auc_score)
    cmx = confusion_matrix(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_pred=predict_labels[test_node_indice])
    print(f"{i}-th fold's auc_score:{auc_score}")
    print(cmx)
    print()
    

==== Training Phase ====
0-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 19, 728]))


SGCN (Loss=0.7162):   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0069): 100%|██████████| 300/300 [00:56<00:00,  5.44it/s]


0         1   2
0    Epoch       AUC  F1
1        1   0.50899   0
2        2  0.565698   0
3        3  0.639004   0
4        4  0.711618   0
5        5  0.748271   0
6        6  0.780775   0
7        7  0.803596   0
8        8  0.821577   0
9        9  0.836791   0
10      10  0.841632   0
11      11  0.850622   0
12      12  0.858921   0
13      13  0.866528   0
14      14   0.87621   0
15      15  0.884509   0
16      16  0.891425   0
17      17  0.899723   0
18      18  0.910788   0
19      19  0.919087   0
20      20  0.925311   0
21      21  0.930844   0
22      22  0.936376   0
23      23  0.941217   0
24      24  0.948824   0
25      25  0.952974   0
26      26  0.959889   0
27      27  0.962656   0
28      28  0.964039   0
29      29  0.967497   0
..     ...       ...  ..
271    271   0.97787   0
272    272  0.975104   0
273    273  0.972337   0
274    274  0.969571   0
275    275  0.966113   0
276    276  0.961964   0
277    277  0.958506   0
278    278  0.955048   0
279    279  0.952974   0
280    280  0.952282   0
281    281  0.954357   0
282    282  0.953665   0
283    283  0.954357   0
284    284  0.951591   0
285    285  0.950899   0
286    286  0.948824   0
287    287   0.94675   0
288    288   0.94675   0
289    289   0.94675   0
290    290  0.949516   0
291    291  0.948824   0
292    292  0.949516   0
293    293  0.950207   0
294    294  0.950899   0
295    295  0.950899   0
296    296  0.950899   0
297    297  0.950899   0
298    298  0.950899   0
299    299  0.950899   0
300    300  0.951591   0

[301 rows x 3 columns]

==== Test Phase ====
0-th fold's auc_score:0.9852670349907918
[[904   1]
 [ 65  28]]

==== Training Phase ====
1-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 21, 745]))


SGCN (Loss=0.7159):   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0056): 100%|██████████| 300/300 [01:04<00:00,  4.74it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.531359   0
2        2  0.555749   0
3        3  0.578397   0
4        4  0.635308   0
5        5  0.689895   0
6        6  0.723577   0
7        7  0.754355   0
8        8  0.785714   0
9        9  0.803136   0
10      10  0.818235   0
11      11   0.83043   0
12      12  0.841463   0
13      13  0.850755   0
14      14  0.862369   0
15      15  0.869919   0
16      16   0.87863   0
17      17  0.881533   0
18      18  0.886179   0
19      19  0.891986   0
20      20  0.896632   0
21      21  0.900116   0
22      22  0.908827   0
23      23  0.911731   0
24      24  0.913473   0
25      25  0.914053   0
26      26  0.915796   0
27      27  0.916376   0
28      28  0.916957   0
29      29  0.916957   0
..     ...       ...  ..
271    271  0.893728   0
272    272  0.893148   0
273    273  0.891405   0
274    274  0.889663   0
275    275  0.890825   0
276    276  0.890825   0
277    277  0.891986   0
278    278  0.891986   0
279    279  0.891405   0
280    280  0.890244   0
281    281  0.890244   0
282    282  0.889082   0
283    283  0.887921   0
284    284   0.88676   0
285    285   0.88676   0
286    286  0.885598   0
287    287  0.885017   0
288    288  0.882695   0
289    289  0.885017   0
290    290  0.876887   0
291    291  0.875145   0
292    292  0.875145   0
293    293   0.87863   0
294    294  0.881533   0
295    295  0.881533   0
296    296   0.87863   0
297    297  0.877468   0
298    298  0.877468   0
299    299  0.877468   0
300    300   0.87921   0

[301 rows x 3 columns]

==== Test Phase ====
1-th fold's auc_score:0.9767937006375487
[[891  13]
 [ 25  68]]

==== Training Phase ====
2-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 33, 754]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0151): 100%|██████████| 300/300 [01:10<00:00,  4.27it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.648777   0
2        2  0.663016   0
3        3  0.698065   0
4        4  0.747718   0
5        5  0.803578   0
6        6  0.838262   0
7        7    0.8682   0
8        8  0.888645   0
9        9  0.899963   0
10      10  0.909456   0
11      11  0.914567   0
12      12  0.917488   0
13      13   0.92479   0
14      14  0.929171   0
15      15  0.932822   0
16      16  0.936108   0
17      17  0.940124   0
18      18   0.94195   0
19      19  0.945966   0
20      20  0.948521   0
21      21  0.950347   0
22      22  0.952537   0
23      23  0.955093   0
24      24  0.956553   0
25      25  0.958379   0
26      26  0.959839   0
27      27  0.961665   0
28      28  0.962395   0
29      29   0.96349   0
..     ...       ...  ..
271    271  0.991968   0
272    272  0.991968   0
273    273  0.991968   0
274    274  0.991968   0
275    275  0.991968   0
276    276  0.991968   0
277    277  0.991968   0
278    278  0.991603   0
279    279  0.991603   0
280    280  0.991603   0
281    281  0.991603   0
282    282  0.991603   0
283    283  0.991603   0
284    284  0.991603   0
285    285  0.991603   0
286    286  0.991603   0
287    287  0.991603   0
288    288  0.991603   0
289    289  0.991968   0
290    290  0.991968   0
291    291  0.991968   0
292    292  0.991968   0
293    293  0.991968   0
294    294  0.991968   0
295    295  0.991968   0
296    296  0.991968   0
297    297  0.991968   0
298    298  0.991968   0
299    299  0.991968   0
300    300  0.992333   0

[301 rows x 3 columns]

==== Test Phase ====
2-th fold's auc_score:0.9437268055952042
[[863  41]
 [ 13  80]]

==== Training Phase ====
3-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 27, 693]))


SGCN (Loss=0.7226):   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0056): 100%|██████████| 300/300 [01:04<00:00,  4.65it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.381853   0
2        2  0.481805   0
3        3  0.594857   0
4        4  0.683649   0
5        5   0.74721   0
6        6  0.786026   0
7        7  0.810771   0
8        8  0.834061   0
9        9  0.851528   0
10      10  0.860747   0
11      11   0.86754   0
12      12  0.876759   0
13      13   0.89083   0
14      14  0.899078   0
15      15  0.905386   0
16      16  0.911208   0
17      17  0.917516   0
18      18  0.920912   0
19      19  0.921397   0
20      20  0.924794   0
21      21   0.92722   0
22      22  0.933527   0
23      23  0.935468   0
24      24  0.936439   0
25      25  0.938865   0
26      26   0.93935   0
27      27  0.939835   0
28      28  0.939835   0
29      29   0.94032   0
..     ...       ...  ..
271    271  0.932072   0
272    272  0.934013   0
273    273  0.934498   0
274    274  0.934013   0
275    275  0.934983   0
276    276  0.935953   0
277    277  0.936924   0
278    278  0.935468   0
279    279  0.937409   0
280    280  0.936924   0
281    281  0.936439   0
282    282  0.935468   0
283    283  0.938379   0
284    284  0.939835   0
285    285   0.93935   0
286    286  0.939835   0
287    287  0.940805   0
288    288  0.936924   0
289    289  0.935953   0
290    290  0.934013   0
291    291  0.936924   0
292    292  0.938865   0
293    293  0.943231   0
294    294  0.943231   0
295    295  0.942746   0
296    296  0.943717   0
297    297  0.942746   0
298    298  0.942746   0
299    299  0.940805   0
300    300   0.94032   0

[301 rows x 3 columns]

==== Test Phase ====
3-th fold's auc_score:0.9693239128366163
[[895   9]
 [ 19  74]]

==== Training Phase ====
4-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 24, 727]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0087): 100%|██████████| 300/300 [01:16<00:00,  4.01it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.447917   0
2        2  0.482292   0
3        3  0.507292   0
4        4  0.539062   0
5        5  0.566146   0
6        6  0.595313   0
7        7     0.625   0
8        8  0.633854   0
9        9  0.646875   0
10      10  0.658333   0
11      11  0.666667   0
12      12  0.682813   0
13      13  0.695833   0
14      14       0.7   0
15      15  0.714583   0
16      16  0.724479   0
17      17  0.732292   0
18      18  0.739062   0
19      19  0.746875   0
20      20  0.764062   0
21      21   0.76875   0
22      22  0.777083   0
23      23  0.782292   0
24      24   0.79375   0
25      25  0.801562   0
26      26  0.806771   0
27      27  0.810937   0
28      28  0.816667   0
29      29  0.822917   0
..     ...       ...  ..
271    271  0.898438   0
272    272  0.897917   0
273    273  0.898958   0
274    274  0.901563   0
275    275  0.902604   0
276    276  0.902083   0
277    277  0.902604   0
278    278  0.904167   0
279    279  0.905729   0
280    280  0.906771   0
281    281  0.908333   0
282    282  0.910937   0
283    283  0.915625   0
284    284  0.921875   0
285    285  0.928646   0
286    286  0.931771   0
287    287  0.934896   0
288    288  0.939583   0
289    289  0.939063   0
290    290  0.935417   0
291    291  0.928646   0
292    292  0.918229   0
293    293    0.9125   0
294    294  0.909896   0
295    295  0.905208   0
296    296  0.901563   0
297    297  0.898438   0
298    298  0.905729   0
299    299  0.913542   0
300    300  0.920833   0

[301 rows x 3 columns]

==== Test Phase ====
4-th fold's auc_score:0.9940289275858789
[[890  14]
 [ 12  81]]

==== Training Phase ====
5-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 26, 632]))


SGCN (Loss=0.7163):   0%|          | 1/300 [00:00<00:55,  5.43it/s]


Training started.



SGCN (Loss=0.0058): 100%|██████████| 300/300 [00:52<00:00,  5.88it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.476874   0
2        2  0.546518   0
3        3  0.643275   0
4        4  0.725678   0
5        5  0.795853   0
6        6  0.838384   0
7        7  0.868687   0
8        8  0.897395   0
9        9  0.916534   0
10      10  0.933546   0
11      11  0.945774   0
12      12  0.952685   0
13      13  0.962786   0
14      14  0.968102   0
15      15  0.969697   0
16      16  0.975013   0
17      17  0.976077   0
18      18  0.978203   0
19      19  0.978735   0
20      20  0.979798   0
21      21  0.979798   0
22      22  0.980861   0
23      23  0.981925   0
24      24  0.981925   0
25      25  0.983519   0
26      26  0.985646   0
27      27  0.985646   0
28      28  0.986178   0
29      29  0.986178   0
..     ...       ...  ..
271    271  0.990962   0
272    272  0.990962   0
273    273  0.990962   0
274    274  0.990962   0
275    275  0.990962   0
276    276  0.990962   0
277    277  0.990962   0
278    278  0.990962   0
279    279  0.990962   0
280    280  0.990962   0
281    281  0.990431   0
282    282  0.990962   0
283    283  0.991494   0
284    284  0.992026   0
285    285  0.992557   0
286    286  0.992557   0
287    287  0.992557   0
288    288  0.992557   0
289    289  0.992557   0
290    290  0.992557   0
291    291  0.992026   0
292    292  0.992026   0
293    293  0.991494   0
294    294  0.991494   0
295    295  0.990962   0
296    296  0.991494   0
297    297  0.991494   0
298    298  0.991494   0
299    299  0.991494   0
300    300  0.991494   0

[301 rows x 3 columns]

==== Test Phase ====
5-th fold's auc_score:0.9810143324355521
[[882  22]
 [ 14  78]]

==== Training Phase ====
6-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 26, 722]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0155): 100%|██████████| 300/300 [01:19<00:00,  3.83it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.379085   0
2        2  0.505135   0
3        3  0.601307   0
4        4  0.672269   0
5        5  0.708683   0
6        6  0.744631   0
7        7  0.773109   0
8        8  0.803922   0
9        9  0.835201   0
10      10   0.85901   0
11      11  0.878151   0
12      12  0.895425   0
13      13  0.911298   0
14      14  0.923903   0
15      15  0.930439   0
16      16  0.936975   0
17      17  0.943044   0
18      18  0.945845   0
19      19  0.950514   0
20      20  0.955182   0
21      21  0.957983   0
22      22  0.960784   0
23      23  0.961718   0
24      24  0.963119   0
25      25  0.964519   0
26      26  0.965453   0
27      27   0.96592   0
28      28  0.966387   0
29      29  0.966387   0
..     ...       ...  ..
271    271  0.944444   0
272    272  0.943978   0
273    273  0.943978   0
274    274  0.943978   0
275    275  0.943978   0
276    276  0.943978   0
277    277  0.942577   0
278    278  0.942577   0
279    279   0.94211   0
280    280   0.94211   0
281    281   0.94211   0
282    282  0.942577   0
283    283   0.94211   0
284    284   0.94211   0
285    285  0.941176   0
286    286  0.941176   0
287    287  0.941643   0
288    288  0.941643   0
289    289  0.941176   0
290    290  0.941643   0
291    291   0.94211   0
292    292  0.943044   0
293    293  0.943978   0
294    294  0.943511   0
295    295  0.943511   0
296    296  0.943044   0
297    297  0.943044   0
298    298   0.94211   0
299    299  0.943511   0
300    300  0.943511   0

[301 rows x 3 columns]

==== Test Phase ====
6-th fold's auc_score:0.9906694882647171
[[904   0]
 [ 54  38]]

==== Training Phase ====
7-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 28, 693]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0055): 100%|██████████| 300/300 [01:13<00:00,  4.15it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.458515   0
2        2  0.585638   0
3        3  0.689471   0
4        4  0.777293   0
5        5  0.846191   0
6        6  0.887433   0
7        7  0.907812   0
8        8  0.920427   0
9        9  0.925279   0
10      10  0.928675   0
11      11  0.931101   0
12      12  0.933042   0
13      13  0.932557   0
14      14  0.934983   0
15      15  0.935953   0
16      16  0.937894   0
17      17  0.937894   0
18      18  0.940805   0
19      19  0.942261   0
20      20  0.944687   0
21      21  0.945657   0
22      22  0.949054   0
23      23  0.951965   0
24      24  0.953906   0
25      25  0.954876   0
26      26  0.956817   0
27      27  0.959243   0
28      28  0.962154   0
29      29  0.963125   0
..     ...       ...  ..
271    271  0.914119   0
272    272  0.913149   0
273    273  0.912664   0
274    274  0.912179   0
275    275  0.911693   0
276    276  0.913634   0
277    277  0.915575   0
278    278   0.91606   0
279    279  0.918486   0
280    280  0.919457   0
281    281  0.918971   0
282    282  0.917516   0
283    283   0.91606   0
284    284   0.91606   0
285    285  0.918001   0
286    286  0.920427   0
287    287  0.922368   0
288    288  0.924309   0
289    289  0.924794   0
290    290  0.925279   0
291    291  0.924309   0
292    292  0.924309   0
293    293  0.924794   0
294    294   0.92722   0
295    295  0.927705   0
296    296  0.929161   0
297    297  0.932072   0
298    298  0.934013   0
299    299  0.934013   0
300    300  0.930616   0

[301 rows x 3 columns]

==== Test Phase ====
7-th fold's auc_score:0.9747138322431704
[[902   2]
 [ 31  61]]

==== Training Phase ====
8-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 31, 735]))


SGCN (Loss=0.7179):   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0124): 100%|██████████| 300/300 [01:07<00:00,  4.42it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.441564   0
2        2  0.611523   0
3        3  0.751852   0
4        4  0.859671   0
5        5  0.922634   0
6        6  0.947325   0
7        7  0.960494   0
8        8  0.968724   0
9        9  0.972428   0
10      10  0.975309   0
11      11  0.978601   0
12      12  0.981481   0
13      13  0.982305   0
14      14  0.983539   0
15      15  0.986008   0
16      16  0.988066   0
17      17  0.988066   0
18      18  0.988066   0
19      19  0.988889   0
20      20  0.990535   0
21      21  0.991358   0
22      22   0.99177   0
23      23   0.99177   0
24      24  0.992181   0
25      25  0.993004   0
26      26  0.993004   0
27      27  0.993416   0
28      28  0.993416   0
29      29  0.993416   0
..     ...       ...  ..
271    271  0.999588   0
272    272  0.999588   0
273    273  0.999588   0
274    274  0.999588   0
275    275  0.999588   0
276    276  0.999588   0
277    277  0.999588   0
278    278  0.999588   0
279    279  0.999588   0
280    280  0.999588   0
281    281  0.999588   0
282    282  0.999588   0
283    283  0.999588   0
284    284  0.999588   0
285    285  0.999588   0
286    286  0.999588   0
287    287  0.999588   0
288    288  0.999588   0
289    289  0.999588   0
290    290  0.999588   0
291    291  0.999588   0
292    292  0.999588   0
293    293  0.999588   0
294    294  0.999588   0
295    295  0.999588   0
296    296  0.999588   0
297    297  0.999588   0
298    298  0.999588   0
299    299  0.999588   0
300    300  0.999588   0

[301 rows x 3 columns]

==== Test Phase ====
8-th fold's auc_score:0.9849220854174683
[[902   2]
 [ 16  76]]

==== Training Phase ====
9-th fold


/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


labels:(array([-1,  1]), array([ 32, 694]))


SGCN (Loss=0.7138):   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0248): 100%|██████████| 300/300 [00:59<00:00,  5.14it/s]


0         1   2
0    Epoch       AUC  F1
1        1  0.554188   0
2        2  0.626042   0
3        3  0.688368   0
4        4  0.757443   0
5        5  0.802303   0
6        6  0.833664   0
7        7  0.850734   0
8        8  0.859865   0
9        9  0.870981   0
10      10  0.879317   0
11      11  0.880111   0
12      12  0.885272   0
13      13  0.890036   0
14      14  0.897975   0
15      15   0.90393   0
16      16  0.910679   0
17      17  0.919015   0
18      18  0.924176   0
19      19  0.932116   0
20      20  0.937674   0
21      21  0.940056   0
22      22  0.945216   0
23      23   0.94998   0
24      24  0.955538   0
25      25  0.958317   0
26      26  0.960699   0
27      27  0.960302   0
28      28  0.962287   0
29      29  0.965462   0
..     ...       ...  ..
271    271  0.961493   0
272    272  0.961096   0
273    273  0.960302   0
274    274  0.960302   0
275    275  0.959905   0
276    276  0.959111   0
277    277  0.959508   0
278    278  0.958714   0
279    279   0.95792   0
280    280  0.957126   0
281    281  0.955538   0
282    282  0.954347   0
283    283  0.954347   0
284    284  0.953553   0
285    285  0.953156   0
286    286  0.951965   0
287    287  0.951568   0
288    288  0.951568   0
289    289  0.951568   0
290    290  0.951568   0
291    291  0.951568   0
292    292  0.951568   0
293    293  0.951171   0
294    294  0.950774   0
295    295  0.950774   0
296    296  0.950774   0
297    297  0.950774   0
298    298  0.950377   0
299    299  0.950377   0
300    300  0.949583   0

[301 rows x 3 columns]

==== Test Phase ====
9-th fold's auc_score:0.9677399961523663
[[904   0]
 [ 18  74]]



In [13]:
np.mean(auc_scores)

0.9768200116159313