# Signed Graph Convolutional Network(SGCN)を用いたFraud User Detection

In [1]:
!git branch

  balance_theory
  balance_theory2
  master
  new_balance_theory2
* subgraph_training_theory2


```sh
pip install -r /home/ubuntu/SGCN/requirements.txt
pip install torch_scatter
pip install torch_sparse
pip install easydict
```


In [2]:
from sgcn import SignedGCNTrainer, SignedGCNPredictor
from parser import parameter_parser
from utils import tab_printer, read_graph, score_printer, save_logs
import easydict
import argparse
import pandas as pd
import numpy as np
import torch
import json
import networkx as nx
from sklearn.metrics import roc_auc_score, roc_curve, auc
from sklearn.metrics import accuracy_score,confusion_matrix
from IPython.display import display
import matplotlib.pyplot as plt
%matplotlib inline

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))


In [ ]:
data_name = input('データセット：')

In [ ]:
args = easydict.EasyDict({
        "edge_path": f'../input/{data_name}/{data_name}_network.csv',
        "features_path":  f'../input/{data_name}/{data_name}_node_feature.csv',
        "nodes_path": f'../input/{data_name}/{data_name}_gt.csv',
        "embedding_path": f'../tmp/embedding/{data_name}_sgcn_feature05.pkl', # tmp folder for cross-validation
        "regression_weights_path": f'../tmp/weights/{data_name}_sgcn_feature05.pkl',
        "inductive_model_path": None, # f'../output/inductive/{data_name}_model', # or None
        "log_path": f'../logs/{data_name}_logs_feature05.json',
        "epochs":300,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 0.0,
        "learning_rate": 0.001,  
        "weight_decay": 10e-4, 
        # "layers": [64, 32,16,8],
        "layers": [32,16],
        "spectral_features":False,
        "general_features": True,  
        "sample_num":None,
        "class_weights":False,
        "node_under_sampling":False,
        "hidden_residual":False,
        "eval_freq":1,
        "subgraph_training":False,
})

In [ ]:
display(pd.io.json.json_normalize(args).T)

## 10-fold cross-validation
- train : validation : test = 6:3:1

In [ ]:
#tab_printer(args)
edges, nodes_dict = read_graph(args) # nodes_dict['indice']:node_id , nodes_dict['label'] : label

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
kf = StratifiedKFold(n_splits=10,shuffle=True,random_state=0)
all_indice = nodes_dict['indice']
all_labels = nodes_dict['label']
auc_scores = []

In [ ]:
for i, (train_index, test_index) in enumerate(kf.split(X=nodes_dict['indice'],y=nodes_dict['label'])):
    print("==== Training Phase ====")
    print(f'{i}-th fold')
    # training
    train_node_indice = all_indice[train_index]
    train_node_labels = all_labels[train_index]
    print(f'labels:{np.unique(train_node_labels,return_counts=True)}')
    tmp_nodes_dict = {}
    tmp_nodes_dict['all_ncount'] = nodes_dict['all_ncount']
    tmp_nodes_dict['indice'] = train_node_indice
    tmp_nodes_dict['label'] = train_node_labels
    trainer = SignedGCNTrainer(args, edges, tmp_nodes_dict)
    trainer.setup_dataset()
    trainer.create_and_train_model()
    
    if args.test_size > 0:
        # trainer.save_model() ## trainer.create_and_train_model()のなかで，すでにbest_modelが保存されている．
        # score_printer(trainer.logs)
        display(pd.DataFrame(trainer.logs['performance']))
        save_logs(args, trainer.logs)

    # test
    print("==== Test Phase ====")
    test_node_indice = all_indice[test_index]
    test_node_labels = all_labels[test_index]
    # feature = pd.read_csv(args.embedding_path,index_col='id').values
    feature = pd.read_pickle(args.embedding_path).drop('id',1).values
    test_feature = feature[test_node_indice]
    # weight = pd.read_csv(args.regression_weights_path)
    weight = pd.read_pickle(args.regression_weights_path)
    predictions = np.dot(test_feature,weight.values.T)
    probabilities = torch.nn.functional.softmax(torch.from_numpy(predictions)).numpy()
    predict_labels = probabilities.argmax(1)
    auc_score = roc_auc_score(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_score=probabilities[:,1])
    auc_scores.append(auc_score)
    cmx = confusion_matrix(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_pred=predict_labels)
    print(f"{i}-th fold's auc_score:{auc_score}")
    print(cmx)
    print()
    

In [ ]:
np.mean(auc_scores)

In [ ]:
_ = plt.hist(probabilities[:,1][test_node_labels==1],alpha=0.5,bins=10)
_ = plt.hist(probabilities[:,1][test_node_labels==-1],alpha=0.5,bins=10)
# plt.xlim(0,0.03)

# new_new_balance_theoryの結果
結果 (32,) (non-class-weights,10e-4, test_size=0.33,lamb=0,lr=0.001)　⬅️これに決定
- amazon :  0.8655989752374083
- alpha : 0.974480519480
- otc : 0.99349

結果 (32,16) (non-class-weights,10e-4, test_size=0.33,lamb=0,lr=0.001)　
- amazon :  0.876279480706
- alpha : 0.977922077922
- otc : 0.99072039072
- epinions : 0.9768200116


結果 (32,16, 8) (non-class-weights,10e-4, test_size=0.33, lamb=0)
- amazon : 0.8786657350643106
- alpha : 
- otc : 

結果 (32,16, 8, 8) (non-class-weights,10e-4, test_size=0.33, lamb=0)
- amazon : 0.8778590500661
- alpha : 
- otc : 



## single-validation

In [ ]:
data_name = input('データセット：')

In [ ]:
args = easydict.EasyDict({
        "edge_path": f'../input/{data_name}/{data_name}_network.csv',
        "features_path":  f'../input/{data_name}/{data_name}_node_feature.csv',
        "nodes_path": f'../input/{data_name}/{data_name}_gt.csv',
        "embedding_path": f'../tmp/embedding/{data_name}_sgcn_feature05.pkl', # tmp folder for cross-validation
        "regression_weights_path": f'../tmp/weights/{data_name}_sgcn_feature05.pkl',
        "inductive_model_path": f'../output/inductive/{data_name}_model', # or None
        "log_path": f'../logs/{data_name}_logs_feature05.json',
        "epochs":300,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 0.0,
        "learning_rate": 0.001,  
        "weight_decay": 10e-4, 
        # "layers": [64, 32,16,8],
        "layers": [32, 16, 8],
        "spectral_features":False,
        "general_features": True,  
        "sample_num":None,
        "class_weights":False,
        "node_under_sampling":False,
        "hidden_residual":False,
        "eval_freq":1,
        "subgraph_training":False,
})

In [ ]:
#tab_printer(args)
edges, nodes_dict = read_graph(args) # nodes_dict['indice']:node_id , nodes_dict['label'] : label

In [ ]:
trainer = SignedGCNTrainer(args, edges, nodes_dict)
trainer.setup_dataset()
trainer.create_and_train_model()

In [ ]:
if args.test_size > 0:
    trainer.save_model()
    # score_printer(trainer.logs)
    display(pd.DataFrame(trainer.logs['performance']))
    save_logs(args, trainer.logs)

## inductive prediction

In [ ]:
data_name = input('データセット：')

In [ ]:
new_args = easydict.EasyDict({
        "edge_path": f'../input/{data_name}/{data_name}_network.csv',
        "features_path":  f'../input/{data_name}/{data_name}_node_feature.csv',
        "nodes_path": f'../input/{data_name}/{data_name}_gt.csv',
        "embedding_path": f'../tmp/embedding/{data_name}_sgcn_feature05.pkl', # tmp folder for cross-validation
        "regression_weights_path": f'../tmp/weights/{data_name}_sgcn_feature05.pkl',
        "inductive_model_path": f'../output/inductive/{data_name}_model', # or None
        "log_path": f'../logs/{data_name}_logs_feature05.json',
        "epochs":300,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 0.0,
        "learning_rate": 0.001,  
        "weight_decay": 10e-4, 
        # "layers": [64, 32,16,8],
        "layers": [32, 16, 8],
        "spectral_features":False,
        "general_features": True,  
        "sample_num":None,
        "class_weights":False,
        "node_under_sampling":False,
        "hidden_residual":False,
        "eval_freq":1,
        "subgraph_training":False,
})

In [ ]:
new_edges, new_nodes_dict = read_graph(new_args)

X = np.array(pd.read_csv(f'../input/{data_name}/{data_name}_node_feature.csv')) # general node features

In [ ]:
training_dataset = input('学習に使ったデータセット：')

In [ ]:
predictor = SignedGCNPredictor(new_args, f'../output/inductive/{training_dataset}_model', X, new_edges,new_nodes_dict)

In [ ]:
predictions = predictor.predict()
predict_labels = predictions.argmax(1)

In [ ]:
y_true = new_nodes_dict['label']

roc_auc_score(y_true=[1 if i==-1 else 0 for i in new_nodes_dict['label']],y_score=predictions[:,1][new_nodes_dict['indice']])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
confusion_matrix([1 if i==-1 else 0 for i in new_nodes_dict['label']],predict_labels[new_nodes_dict['indice']])

In [ ]:
_ = plt.hist(predictions[:,1][new_nodes_dict['indice']][y_true==1],alpha=0.5,bins=10)
_ = plt.hist(predictions[:,1][new_nodes_dict['indice']][y_true==-1],alpha=0.5,bins=10)

## epinions dataset

In [ ]:
data_name = 'epinions'

In [ ]:
args = easydict.EasyDict({
        "edge_path": f'../input/{data_name}/{data_name}_network.csv',#'../input/{data_name}/user_network.csv',
        "features_path":  f'../input/{data_name}/{data_name}_node_feature.csv',#'../input/{data_name}/user_network.csv',
        "nodes_path": f'../input/{data_name}/{data_name}_gt.csv',
        "embedding_path": f'../tmp/embedding/{data_name}_sgcn_feature05.pkl', # tmp folder for cross-validation
        "regression_weights_path": f'../tmp/weights/{data_name}_sgcn_feature05.pkl',
        "inductive_model_path": f'../output/inductive/{data_name}_model', # or None
        "log_path": f'../logs/{data_name}_logs_feature05.json',
        "epochs":300,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 0.0,
        "learning_rate": 0.001,  
        "weight_decay": 10e-4, 
        # "layers": [64, 32,16,8],
        "layers": [32, 16],
        "spectral_features":False,
        "general_features": True,  
        "sample_num":None,
        "class_weights":False,
        "node_under_sampling":False,
        "hidden_residual":False,
        "eval_freq":1,
        "subgraph_training":True,
})

In [ ]:
display(pd.io.json.json_normalize(args).T)

In [ ]:
#tab_printer(args)
edges, nodes_dict = read_graph(args) # nodes_dict['indice']:node_id , nodes_dict['label'] : label

In [ ]:
test_X = np.array(pd.read_csv(args.features_path))

In [ ]:
def subgraph_making(args,edges,nodes_dict,sample_node_num,train_node_indice_original):
    original_network_df = pd.read_csv(args.edge_path)

    sampled_node_indice = set(np.random.choice(np.arange(nodes_dict['all_ncount']), sample_node_num, replace=False)) | set(train_node_indice_original)

    sub_network_df = \
        original_network_df.loc[(original_network_df.id1_.isin(sampled_node_indice)) & (original_network_df.id2_.isin(sampled_node_indice))]

    original_gt_df = pd.read_csv(args.nodes_path)

    sub_gt_df = \
        original_gt_df.copy().loc[(original_gt_df.node_id.isin(sub_network_df.id1_)) & (original_gt_df.node_id.isin(sub_network_df.id2_))]

    from sklearn.preprocessing import LabelEncoder

    subGraph_map_encoder = LabelEncoder()

    subGraph_map_encoder.fit(list(set(sub_network_df.id1_) | set(sub_network_df.id2_) | set(sub_gt_df.node_id)))

    sub_gt_df['node_id'] = subGraph_map_encoder.transform(sub_gt_df.node_id)

    sub_network_df['id1_'] = subGraph_map_encoder.transform(sub_network_df.id1_)

    sub_network_df['id2_'] = subGraph_map_encoder.transform(sub_network_df.id2_)

    sub_edges = {}

    sub_edges['positive_edges'] = sub_network_df.loc[sub_network_df.weight==1,['id1_','id2_']].values.tolist()

    sub_edges['negative_edges'] = sub_network_df.loc[sub_network_df.weight==-1,['id1_','id2_']].values.tolist()

    sub_edges['ecount'] = len(sub_network_df)

    sub_edges['ncount'] = len(set(sub_network_df['id1_']) | set(sub_network_df['id2_']))

    sub_nodes_dict = {}

    sub_nodes_dict['indice'] = sub_gt_df.node_id.values
    sub_nodes_dict['label'] = sub_gt_df.label.values

    sub_nodes_dict['all_ncount'] = len(set(sub_network_df.id1_) | set(sub_network_df.id2_) | set(sub_gt_df.node_id))

    sub_nodes_dict['subgraph_map_from_original_feature'] = subGraph_map_encoder.classes_    
    return sub_edges, sub_nodes_dict, subGraph_map_encoder

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=10,shuffle=True, random_state=0)
all_indice = nodes_dict['indice']
all_labels = nodes_dict['label']
auc_scores = []

In [ ]:
# train : 90 % cross-validation
for i, (train_index, test_index) in enumerate(kf.split(X=nodes_dict['indice'],y=nodes_dict['label'])):
    print("==== Training Phase ====")
    print(f'{i}-th fold')
    # training
    train_node_indice_original = all_indice[train_index] #⬅️これは元々のグラフのnode_indice

    # extract sub-graph
    sub_edges, sub_nodes_dict,subGraph_map_encoder = subgraph_making(args,edges,nodes_dict,20000, [])
                                                                     # np.random.choice(train_node_indice_original,1000))
    
    train_indice_boolean_judger = np.isin(subGraph_map_encoder.inverse_transform(sub_nodes_dict['indice']),train_node_indice_original)
    train_node_indice = sub_nodes_dict['indice'][train_indice_boolean_judger]
    train_node_labels = sub_nodes_dict['label'][train_indice_boolean_judger]
    print(f'labels:{np.unique(train_node_labels,return_counts=True)}')
    tmp_nodes_dict = {}
    tmp_nodes_dict['all_ncount'] = sub_nodes_dict['all_ncount']
    tmp_nodes_dict['indice'] = train_node_indice
    tmp_nodes_dict['label'] = train_node_labels
    tmp_nodes_dict['subgraph_map_from_original_feature'] = subGraph_map_encoder.classes_
    trainer = SignedGCNTrainer(args, sub_edges, tmp_nodes_dict)
    trainer.setup_dataset()
    trainer.create_and_train_model()
    
    if args.test_size > 0:
        # trainer.save_model() ## trainer.create_and_train_model()のなかで，すでにbest_modelが保存されている．
        # score_printer(trainer.logs)
        display(pd.DataFrame(trainer.logs['performance']))
        save_logs(args, trainer.logs)

    # test
    print("==== Test Phase ====")
    test_node_indice = all_indice[test_index]
    test_node_labels = all_labels[test_index]
    predictor = SignedGCNPredictor(args, args.inductive_model_path, test_X, edges,nodes_dict)
    predictions = predictor.predict()
    predict_labels = predictions.argmax(1)
    auc_score = roc_auc_score(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_score=predictions[:,1][test_node_indice])
    auc_scores.append(auc_score)
    cmx = confusion_matrix(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_pred=predict_labels[test_node_indice])
    print(f"{i}-th fold's auc_score:{auc_score}")
    print(cmx)
    print()
    

In [ ]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=10,shuffle=True, random_state=0)
all_indice = nodes_dict['indice']
all_labels = nodes_dict['label']
auc_scores = []

In [ ]:
# train : 10 % cross-validation
for i, (test_index, train_index) in enumerate(kf.split(X=nodes_dict['indice'],y=nodes_dict['label'])):
    print("==== Training Phase ====")
    print(f'{i}-th fold')
    # training
    train_node_indice_original = all_indice[train_index] #⬅️これは元々のグラフのnode_indice

    # extract sub-graph
    sub_edges, sub_nodes_dict,subGraph_map_encoder = subgraph_making(args,edges,nodes_dict, 20000, 
                                                                     np.random.choice(train_node_indice_original,1000,replace=False))
    
    train_indice_boolean_judger = np.isin(subGraph_map_encoder.inverse_transform(sub_nodes_dict['indice']),train_node_indice_original)
    train_node_indice = sub_nodes_dict['indice'][train_indice_boolean_judger]
    train_node_labels = sub_nodes_dict['label'][train_indice_boolean_judger]
    print(f'labels:{np.unique(train_node_labels,return_counts=True)}')
    tmp_nodes_dict = {}
    tmp_nodes_dict['all_ncount'] = sub_nodes_dict['all_ncount']
    tmp_nodes_dict['indice'] = train_node_indice
    tmp_nodes_dict['label'] = train_node_labels
    tmp_nodes_dict['subgraph_map_from_original_feature'] = subGraph_map_encoder.classes_
    trainer = SignedGCNTrainer(args, sub_edges, tmp_nodes_dict)
    trainer.setup_dataset()
    trainer.create_and_train_model()
    
    if args.test_size > 0:
        # trainer.save_model() ## trainer.create_and_train_model()のなかで，すでにbest_modelが保存されている．
        # score_printer(trainer.logs)
        display(pd.DataFrame(trainer.logs['performance']))
        save_logs(args, trainer.logs)

    # test
    print("==== Test Phase ====")
    test_node_indice = all_indice[test_index]
    test_node_labels = all_labels[test_index]
    predictor = SignedGCNPredictor(args, args.inductive_model_path, test_X, edges,nodes_dict)
    predictions = predictor.predict()
    predict_labels = predictions.argmax(1)
    auc_score = roc_auc_score(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_score=predictions[:,1][test_node_indice])
    auc_scores.append(auc_score)
    cmx = confusion_matrix(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_pred=predict_labels[test_node_indice])
    print(f"{i}-th fold's auc_score:{auc_score}")
    print(cmx)
    print()
    

In [ ]:
np.mean(auc_scores)

# ロバストネスの検証

In [3]:
data_name = input('データセット：')

データセット：amazon


In [4]:
args = easydict.EasyDict({
        "edge_path": f'../input/{data_name}/{data_name}_network.csv',
        "features_path":  f'../input/{data_name}/{data_name}_node_feature.csv',
        "nodes_path": f'../input/{data_name}/{data_name}_gt.csv',
        "embedding_path": f'../tmp/embedding/{data_name}_sgcn_feature05.pkl', # tmp folder for cross-validation
        "regression_weights_path": f'../tmp/weights/{data_name}_sgcn_feature05.pkl',
        "inductive_model_path": None, # f'../output/inductive/{data_name}_model', # or None
        "log_path": f'../logs/{data_name}_logs_feature05.json',
        "epochs":300,
        "test_size":0.33,
        "reduction_iterations": 128,
        "reduction_dimensions": 30,
        "seed": 42,
        "lamb": 0.0,
        "learning_rate": 0.001,  
        "weight_decay": 10e-4, 
        # "layers": [64, 32,16,8],
        "layers": [32,16, 8],
        "spectral_features":False,
        "general_features": True,  
        "sample_num":None,
        "class_weights":False,
        "node_under_sampling":False,
        "hidden_residual":False,
        "eval_freq":1,
        "subgraph_training":False,
})

In [5]:
#tab_printer(args)
edges, nodes_dict = read_graph(args) # nodes_dict['indice']:node_id , nodes_dict['label'] : label

In [6]:
from sklearn.model_selection import StratifiedKFold

In [7]:
kf = StratifiedKFold(n_splits=10,shuffle=True,random_state=0)
all_indice = nodes_dict['indice']
all_labels = nodes_dict['label']
auc_scores = []

In [8]:
for i, (test_index, train_index) in enumerate(kf.split(X=nodes_dict['indice'],y=nodes_dict['label'])): # trainとtestを逆にする
    print("==== Training Phase ====")
    print(f'{i}-th fold')
    # training
    train_node_indice = all_indice[train_index]
    train_node_labels = all_labels[train_index]
    print(f'labels:{np.unique(train_node_labels,return_counts=True)}')
    tmp_nodes_dict = {}
    tmp_nodes_dict['all_ncount'] = nodes_dict['all_ncount']
    tmp_nodes_dict['indice'] = train_node_indice
    tmp_nodes_dict['label'] = train_node_labels
    trainer = SignedGCNTrainer(args, edges, tmp_nodes_dict)
    trainer.setup_dataset()
    trainer.create_and_train_model()
    
    if args.test_size > 0:
        # trainer.save_model() ## trainer.create_and_train_model()のなかで，すでにbest_modelが保存されている．
        # score_printer(trainer.logs)
        display(pd.DataFrame(trainer.logs['performance']))
        save_logs(args, trainer.logs)

    # test
    print("==== Test Phase ====")
    test_node_indice = all_indice[test_index]
    test_node_labels = all_labels[test_index]
    # feature = pd.read_csv(args.embedding_path,index_col='id').values
    feature = pd.read_pickle(args.embedding_path).drop('id',1).values
    test_feature = feature[test_node_indice]
    # weight = pd.read_csv(args.regression_weights_path)
    weight = pd.read_pickle(args.regression_weights_path)
    predictions = np.dot(test_feature,weight.values.T)
    probabilities = torch.nn.functional.softmax(torch.from_numpy(predictions)).numpy()
    predict_labels = probabilities.argmax(1)
    auc_score = roc_auc_score(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_score=probabilities[:,1])
    auc_scores.append(auc_score)
    cmx = confusion_matrix(y_true=[1 if i==-1 else 0 for i in test_node_labels],y_pred=predict_labels)
    print(f"{i}-th fold's auc_score:{auc_score}")
    print(cmx)
    print()
    

==== Training Phase ====
0-th fold
labels:(array([-1,  1]), array([ 25, 236]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0827): 100%|██████████| 300/300 [09:36<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.656646   0
2        2  0.768987   0
3        3  0.841772   0
4        4  0.897152   0
5        5  0.917722   0
6        6  0.916139   0
7        7  0.914557   0
8        8  0.922468   0
9        9  0.922468   0
10      10  0.927215   0
11      11  0.928797   0
12      12  0.928797   0
13      13  0.933544   0
14      14  0.931962   0
15      15  0.931962   0
16      16  0.931962   0
17      17  0.931962   0
18      18  0.931962   0
19      19  0.933544   0
20      20  0.935127   0
21      21  0.935127   0
22      22  0.935127   0
23      23  0.935127   0
24      24  0.935127   0
25      25  0.931962   0
26      26  0.931962   0
27      27  0.933544   0
28      28  0.933544   0
29      29  0.933544   0
..     ...       ...  ..
271    271  0.797468   0
272    272  0.780063   0
273    273   0.77057   0
274    274   0.77057   0
275    275  0.778481   0
276    276  0.791139   0
277    277  0.800633   0
278    278  0.795886   0
279    279  0.787975   0
280    280  0.776899   0
281    281  0.775316   0
282    282  0.780063   0
283    283  0.789557   0
284    284  0.803797   0
285    285  0.792722   0
286    286  0.780063   0
287    287  0.765823   0
288    288  0.761076   0
289    289  0.767405   0
290    290  0.776899   0
291    291   0.77057   0
292    292  0.767405   0
293    293  0.761076   0
294    294  0.751582   0
295    295  0.756329   0
296    296  0.754747   0
297    297  0.754747   0
298    298  0.753165   0
299    299  0.748418   0
300    300  0.748418   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
0-th fold's auc_score:0.8268819597165498
[[2122    0]
 [ 216    0]]

==== Training Phase ====
1-th fold
labels:(array([-1,  1]), array([ 24, 236]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0927): 100%|██████████| 300/300 [09:29<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.647436   0
2        2  0.814103   0
3        3  0.847756   0
4        4  0.862179   0
5        5  0.865385   0
6        6  0.879808   0
7        7  0.873397   0
8        8  0.876603   0
9        9  0.870192   0
10      10  0.870192   0
11      11  0.866987   0
12      12  0.860577   0
13      13  0.857372   0
14      14  0.855769   0
15      15  0.854167   0
16      16  0.854167   0
17      17  0.852564   0
18      18  0.855769   0
19      19  0.855769   0
20      20  0.855769   0
21      21  0.855769   0
22      22  0.854167   0
23      23  0.854167   0
24      24  0.852564   0
25      25  0.850962   0
26      26  0.849359   0
27      27  0.847756   0
28      28  0.841346   0
29      29  0.841346   0
..     ...       ...  ..
271    271  0.753205   0
272    272      0.75   0
273    273  0.758013   0
274    274  0.761218   0
275    275  0.762821   0
276    276  0.753205   0
277    277  0.751603   0
278    278      0.75   0
279    279  0.745192   0
280    280  0.725962   0
281    281  0.746795   0
282    282  0.741987   0
283    283  0.724359   0
284    284  0.737179   0
285    285  0.730769   0
286    286  0.708333   0
287    287  0.653846   0
288    288  0.733974   0
289    289  0.732372   0
290    290  0.706731   0
291    291  0.717949   0
292    292  0.708333   0
293    293  0.695513   0
294    294  0.655449   0
295    295  0.669872   0
296    296  0.705128   0
297    297  0.732372   0
298    298  0.729167   0
299    299  0.721154   0
300    300  0.717949   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
1-th fold's auc_score:0.8450878876983283
[[2122    0]
 [ 217    0]]

==== Training Phase ====
2-th fold
labels:(array([-1,  1]), array([ 24, 236]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0745): 100%|██████████| 300/300 [09:45<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.626603   0
2        2  0.661859   0
3        3  0.679487   0
4        4  0.658654   0
5        5  0.628205   0
6        6  0.613782   0
7        7  0.605769   0
8        8  0.600962   0
9        9  0.594551   0
10      10  0.591346   0
11      11  0.592949   0
12      12  0.596154   0
13      13  0.597756   0
14      14  0.610577   0
15      15  0.616987   0
16      16  0.620192   0
17      17  0.623397   0
18      18  0.623397   0
19      19     0.625   0
20      20  0.628205   0
21      21  0.636218   0
22      22  0.636218   0
23      23  0.634615   0
24      24  0.633013   0
25      25  0.636218   0
26      26  0.637821   0
27      27  0.639423   0
28      28  0.639423   0
29      29  0.639423   0
..     ...       ...  ..
271    271  0.790064   0
272    272  0.774038   0
273    273  0.766026   0
274    274  0.774038   0
275    275  0.791667   0
276    276  0.769231   0
277    277  0.785256   0
278    278  0.793269   0
279    279  0.798077   0
280    280  0.801282   0
281    281  0.793269   0
282    282  0.769231   0
283    283  0.758013   0
284    284  0.767628   0
285    285  0.782051   0
286    286  0.780449   0
287    287  0.791667   0
288    288  0.785256   0
289    289  0.782051   0
290    290  0.782051   0
291    291  0.777244   0
292    292  0.775641   0
293    293  0.772436   0
294    294  0.767628   0
295    295  0.775641   0
296    296  0.786859   0
297    297  0.785256   0
298    298  0.778846   0
299    299  0.777244   0
300    300  0.793269   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
2-th fold's auc_score:0.7429713729765416
[[2072   50]
 [ 160   57]]

==== Training Phase ====
3-th fold
labels:(array([-1,  1]), array([ 24, 236]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0323): 100%|██████████| 300/300 [09:35<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.720353   0
2        2  0.840545   0
3        3  0.862981   0
4        4  0.880609   0
5        5  0.882212   0
6        6  0.880609   0
7        7  0.877404   0
8        8  0.875801   0
9        9  0.874199   0
10      10  0.880609   0
11      11  0.877404   0
12      12  0.877404   0
13      13  0.872596   0
14      14  0.869391   0
15      15  0.870994   0
16      16  0.870994   0
17      17  0.869391   0
18      18  0.869391   0
19      19  0.869391   0
20      20  0.867788   0
21      21  0.866186   0
22      22  0.867788   0
23      23  0.866186   0
24      24  0.866186   0
25      25  0.866186   0
26      26  0.861378   0
27      27  0.854968   0
28      28  0.851763   0
29      29  0.838942   0
..     ...       ...  ..
271    271  0.848558   0
272    272  0.851763   0
273    273  0.851763   0
274    274  0.851763   0
275    275  0.851763   0
276    276   0.85016   0
277    277  0.846955   0
278    278  0.845353   0
279    279  0.845353   0
280    280   0.84375   0
281    281  0.829327   0
282    282  0.821314   0
283    283  0.814904   0
284    284  0.808494   0
285    285  0.805288   0
286    286  0.805288   0
287    287  0.805288   0
288    288  0.803686   0
289    289  0.805288   0
290    290  0.805288   0
291    291  0.805288   0
292    292  0.803686   0
293    293  0.803686   0
294    294  0.802083   0
295    295  0.802083   0
296    296  0.802083   0
297    297  0.798878   0
298    298  0.797276   0
299    299  0.797276   0
300    300  0.798878   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
3-th fold's auc_score:0.8436154918627328
[[1966  156]
 [ 124   93]]

==== Training Phase ====
4-th fold
labels:(array([-1,  1]), array([ 24, 236]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0407): 100%|██████████| 300/300 [09:41<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.408654   0
2        2  0.620192   0
3        3  0.758013   0
4        4  0.831731   0
5        5  0.823718   0
6        6  0.833333   0
7        7  0.855769   0
8        8  0.858974   0
9        9  0.860577   0
10      10  0.866987   0
11      11  0.866987   0
12      12   0.86859   0
13      13  0.866987   0
14      14  0.849359   0
15      15  0.849359   0
16      16  0.849359   0
17      17  0.849359   0
18      18  0.849359   0
19      19  0.849359   0
20      20  0.849359   0
21      21  0.849359   0
22      22  0.849359   0
23      23  0.849359   0
24      24  0.849359   0
25      25  0.849359   0
26      26  0.849359   0
27      27  0.849359   0
28      28  0.849359   0
29      29  0.850962   0
..     ...       ...  ..
271    271  0.953526   0
272    272  0.951923   0
273    273  0.950321   0
274    274  0.929487   0
275    275  0.929487   0
276    276   0.93109   0
277    277  0.948718   0
278    278  0.951923   0
279    279  0.951923   0
280    280  0.953526   0
281    281  0.951923   0
282    282  0.948718   0
283    283  0.945513   0
284    284  0.945513   0
285    285  0.947115   0
286    286  0.947115   0
287    287  0.947115   0
288    288  0.950321   0
289    289  0.932692   0
290    290   0.93109   0
291    291   0.93109   0
292    292  0.927885   0
293    293  0.927885   0
294    294  0.927885   0
295    295  0.927885   0
296    296  0.927885   0
297    297  0.924679   0
298    298  0.923077   0
299    299  0.921474   0
300    300  0.923077   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
4-th fold's auc_score:0.8622126330694024
[[2012  110]
 [ 117  100]]

==== Training Phase ====
5-th fold
labels:(array([-1,  1]), array([ 24, 236]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0436): 100%|██████████| 300/300 [09:36<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.512821   0
2        2  0.717949   0
3        3  0.780449   0
4        4  0.786859   0
5        5  0.791667   0
6        6  0.785256   0
7        7  0.785256   0
8        8  0.782051   0
9        9  0.788462   0
10      10  0.796474   0
11      11  0.794872   0
12      12  0.802885   0
13      13  0.801282   0
14      14  0.801282   0
15      15  0.801282   0
16      16   0.80609   0
17      17  0.807692   0
18      18  0.809295   0
19      19  0.807692   0
20      20  0.810897   0
21      21  0.814103   0
22      22    0.8125   0
23      23    0.8125   0
24      24  0.810897   0
25      25  0.809295   0
26      26  0.820513   0
27      27  0.820513   0
28      28  0.820513   0
29      29  0.820513   0
..     ...       ...  ..
271    271  0.844551   0
272    272  0.844551   0
273    273  0.844551   0
274    274  0.841346   0
275    275  0.841346   0
276    276  0.841346   0
277    277  0.841346   0
278    278  0.836538   0
279    279  0.838141   0
280    280  0.836538   0
281    281  0.836538   0
282    282  0.828526   0
283    283  0.830128   0
284    284  0.831731   0
285    285  0.830128   0
286    286  0.831731   0
287    287  0.838141   0
288    288  0.838141   0
289    289  0.836538   0
290    290  0.842949   0
291    291  0.844551   0
292    292  0.841346   0
293    293  0.839744   0
294    294  0.836538   0
295    295  0.831731   0
296    296  0.828526   0
297    297  0.826923   0
298    298  0.830128   0
299    299  0.834936   0
300    300  0.834936   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
5-th fold's auc_score:0.8582395531560957
[[2043   79]
 [ 133   84]]

==== Training Phase ====
6-th fold
labels:(array([-1,  1]), array([ 24, 236]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.1611): 100%|██████████| 300/300 [09:30<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.584135   0
2        2  0.737981   0
3        3  0.818109   0
4        4  0.854968   0
5        5  0.870994   0
6        6  0.872596   0
7        7  0.874199   0
8        8  0.870994   0
9        9  0.864583   0
10      10  0.862981   0
11      11  0.858173   0
12      12  0.856571   0
13      13  0.856571   0
14      14  0.848558   0
15      15  0.851763   0
16      16  0.846955   0
17      17  0.846955   0
18      18  0.853365   0
19      19  0.846955   0
20      20   0.84375   0
21      21  0.842147   0
22      22  0.846955   0
23      23  0.845353   0
24      24  0.848558   0
25      25  0.842147   0
26      26  0.840545   0
27      27  0.840545   0
28      28   0.84375   0
29      29   0.84375   0
..     ...       ...  ..
271    271  0.752404   0
272    272  0.754006   0
273    273  0.755609   0
274    274  0.755609   0
275    275  0.757212   0
276    276  0.750801   0
277    277  0.749199   0
278    278  0.752404   0
279    279  0.752404   0
280    280  0.752404   0
281    281  0.750801   0
282    282  0.754006   0
283    283  0.755609   0
284    284  0.755609   0
285    285  0.752404   0
286    286  0.754006   0
287    287  0.757212   0
288    288  0.758814   0
289    289  0.760417   0
290    290  0.760417   0
291    291  0.800481   0
292    292  0.808494   0
293    293  0.798878   0
294    294  0.805288   0
295    295  0.806891   0
296    296  0.805288   0
297    297  0.798878   0
298    298  0.782853   0
299    299  0.771635   0
300    300  0.770032   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
6-th fold's auc_score:0.848217271767787
[[2122    0]
 [ 217    0]]

==== Training Phase ====
7-th fold
labels:(array([-1,  1]), array([ 24, 236]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0743): 100%|██████████| 300/300 [09:33<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.551282   0
2        2  0.735577   0
3        3  0.798077   0
4        4  0.830128   0
5        5  0.849359   0
6        6  0.855769   0
7        7  0.858974   0
8        8  0.862179   0
9        9  0.862179   0
10      10  0.865385   0
11      11  0.865385   0
12      12  0.865385   0
13      13  0.865385   0
14      14  0.863782   0
15      15  0.862179   0
16      16  0.860577   0
17      17  0.860577   0
18      18  0.855769   0
19      19  0.852564   0
20      20  0.852564   0
21      21  0.850962   0
22      22  0.849359   0
23      23  0.846154   0
24      24  0.846154   0
25      25  0.846154   0
26      26  0.844551   0
27      27  0.846154   0
28      28  0.844551   0
29      29  0.844551   0
..     ...       ...  ..
271    271  0.676282   0
272    272  0.674679   0
273    273  0.674679   0
274    274  0.674679   0
275    275  0.669872   0
276    276  0.668269   0
277    277  0.669872   0
278    278  0.669872   0
279    279  0.668269   0
280    280  0.668269   0
281    281  0.668269   0
282    282  0.665064   0
283    283  0.668269   0
284    284  0.668269   0
285    285  0.668269   0
286    286  0.668269   0
287    287  0.666667   0
288    288  0.665064   0
289    289  0.663462   0
290    290  0.665064   0
291    291  0.663462   0
292    292  0.663462   0
293    293  0.663462   0
294    294  0.665064   0
295    295  0.665064   0
296    296  0.663462   0
297    297  0.657051   0
298    298  0.657051   0
299    299  0.658654   0
300    300  0.653846   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
7-th fold's auc_score:0.8411202369732058
[[2063   59]
 [ 145   72]]

==== Training Phase ====
8-th fold
labels:(array([-1,  1]), array([ 24, 235]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.043): 100%|██████████| 300/300 [09:35<00:00,  1.89s/it] 


0         1   2
0    Epoch       AUC  F1
1        1  0.544071   0
2        2  0.637019   0
3        3  0.741186   0
4        4  0.747596   0
5        5  0.758814   0
6        6  0.771635   0
7        7  0.790865   0
8        8  0.806891   0
9        9  0.806891   0
10      10  0.810096   0
11      11  0.814904   0
12      12  0.813301   0
13      13  0.814904   0
14      14  0.814904   0
15      15  0.814904   0
16      16  0.826122   0
17      17  0.832532   0
18      18   0.83734   0
19      19   0.83734   0
20      20  0.835737   0
21      21  0.835737   0
22      22  0.835737   0
23      23   0.83734   0
24      24  0.842147   0
25      25  0.842147   0
26      26  0.845353   0
27      27  0.846955   0
28      28  0.846955   0
29      29  0.846955   0
..     ...       ...  ..
271    271  0.797276   0
272    272  0.797276   0
273    273  0.797276   0
274    274  0.798878   0
275    275  0.802083   0
276    276  0.806891   0
277    277  0.803686   0
278    278  0.803686   0
279    279  0.794071   0
280    280  0.802083   0
281    281  0.802083   0
282    282  0.803686   0
283    283  0.803686   0
284    284  0.800481   0
285    285  0.798878   0
286    286  0.800481   0
287    287  0.803686   0
288    288  0.803686   0
289    289  0.811699   0
290    290  0.810096   0
291    291  0.806891   0
292    292  0.800481   0
293    293  0.803686   0
294    294  0.798878   0
295    295  0.800481   0
296    296  0.803686   0
297    297  0.810096   0
298    298  0.811699   0
299    299  0.811699   0
300    300  0.805288   0

[301 rows x 3 columns]

/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


==== Test Phase ====
8-th fold's auc_score:0.8287778576095475
[[2123    0]
 [ 217    0]]

==== Training Phase ====
9-th fold
labels:(array([-1,  1]), array([ 24, 235]))


Loss:   0%|          | 0/300 [00:00<?, ?it/s]


Training started.



SGCN (Loss=0.0644): 100%|██████████| 300/300 [09:34<00:00,  1.89s/it]


0         1   2
0    Epoch       AUC  F1
1        1  0.689103   0
2        2  0.782051   0
3        3  0.786859   0
4        4  0.785256   0
5        5  0.788462   0
6        6  0.780449   0
7        7  0.780449   0
8        8  0.783654   0
9        9  0.783654   0
10      10  0.810897   0
11      11  0.815705   0
12      12   0.81891   0
13      13   0.81891   0
14      14  0.820513   0
15      15   0.81891   0
16      16  0.820513   0
17      17  0.807692   0
18      18  0.804487   0
19      19   0.80609   0
20      20  0.807692   0
21      21  0.807692   0
22      22  0.799679   0
23      23  0.801282   0
24      24  0.814103   0
25      25  0.815705   0
26      26  0.823718   0
27      27  0.823718   0
28      28  0.825321   0
29      29    0.8125   0
..     ...       ...  ..
271    271  0.780449   0
272    272  0.782051   0
273    273  0.788462   0
274    274  0.786859   0
275    275  0.793269   0
276    276  0.790064   0
277    277  0.785256   0
278    278  0.785256   0
279    279  0.777244   0
280    280  0.767628   0
281    281  0.775641   0
282    282  0.775641   0
283    283  0.772436   0
284    284  0.767628   0
285    285  0.761218   0
286    286  0.753205   0
287    287   0.74359   0
288    288  0.738782   0
289    289  0.741987   0
290    290  0.751603   0
291    291  0.761218   0
292    292  0.766026   0
293    293  0.762821   0
294    294  0.761218   0
295    295  0.761218   0
296    296  0.762821   0
297    297  0.764423   0
298    298  0.769231   0
299    299  0.774038   0
300    300  0.785256   0

[301 rows x 3 columns]

==== Test Phase ====
9-th fold's auc_score:0.8353614461754192
[[2055   68]
 [ 160   57]]



/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/ipykernel/__main__.py:32: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.


In [9]:
np.mean(auc_scores)

0.833248571100561